apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ include "murder-bird.name" . }}
  labels:
    {{- include "murder-bird.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "murder-bird.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
